; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25507.1 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\Michael\AppData\Local\Temp\.NETFramework,Version=v4.5.2.AssemblyAttributes.cpp"
